[workspace]
authors = ["Rogério Ferreira <rogerioferreira.dsf@gmail.com>"]
channels = ["conda-forge"]
name = "MVP-Análise de Dados e Boas Práticas-PUC-RIO"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
autogluon = "1.5.*"
python = ">=3.12.13,<3.13"
pandas = ">=2.3.3,<3"
jupyterlab = ">=4.5.6,<5"
ipykernel = ">=7.2.0,<8"
pip = ">=26.0.1,<27"
scikit-learn = ">=1.7.2,<2"
